services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
    networks:
      - app-network

  populate:
    build: ./server
    container_name: populate
    command: ["node", "populate/populate.js"]
    depends_on:
      - mongo
    env_file:
      - .env
    restart: "no"
    networks:
      - app-network

  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
      - populate
    restart: unless-stopped
    networks:
      - app-network

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge