apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-backend
  template:
    metadata:
      labels:
        app: employee-backend
    spec:
      containers:
        - name: employee-backend
          image: faboknorbert/employee-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: mongo-uri
---
apiVersion: v1
kind: Service
metadata:
  name: employee-backend-service
spec:
  type: ClusterIP
  selector:
    app: employee-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000