apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-frontend
  template:
    metadata:
      labels:
        app: employee-frontend
    spec:
      containers:
        - name: employee-frontend
          image: faboknorbert/employee-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: employee-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: employee-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
